sudo: false

language: node_js
node_js: node

cache:
  directories:
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts
    - demo/elm-stuff/build-artifacts
    - node_modules
    - sysconfcpus

os:
  - linux

env:
  global:
    - ELM_VERSION="0.18.0"
    - ELM_TEST_VERSION="0.18.7"
    - SYSCONFCPUS="${TRAVIS_BUILD_DIR}/sysconfcpus/bin/sysconfcpus -n 2"
    - ELM="${TRAVIS_BUILD_DIR}/node_modules/.bin/elm"
    - ELM_TEST="node ${TRAVIS_BUILD_DIR}/node_modules/elm-test/bin/elm-test"

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - npm install elm@$ELM_VERSION elm-test@$ELM_TEST_VERSION
  # Faster compile on Travis.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

script:
  - $SYSCONFCPUS $ELM_TEST
  - bash ./demo/deploy.sh
