name: Build and Deploy
on:
  push: 
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Test
      uses: jorelali/setup-elm@v1
      with:
        elm-version: 0.19.1
      run: |
        npm install elm-test
        node node_modules/elm-test/bin/elm-test

    - name: Build Demo
      run: |
        cd demo
        npm install
        npm run build
        cd ..

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: demo/build
        CLEAN: true
